version: "3"
services:

  northwind-webapi:
    image: "giovanidecusati/northwind-webapi:0.0.1"
    ports: 
      - "5000:80"
    depends_on:
      - northwind-sql
  northwind-sql:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "12QWaszx@@34"
        ACCEPT_EULA: "Y"